FROM eclipse-temurin:17.0.7_7-jre
ENV PLANTUML_VERSION=1.2023.7
ENV LANG en_US.UTF-8
RUN apt-get update && \
    apt-get install -y \
        graphviz \
        wget \
        ca-certificates \
        fonts-dejavu \
        fontconfig && \
    wget "http://downloads.sourceforge.net/project/plantuml/${PLANTUML_VERSION}/plantuml.${PLANTUML_VERSION}.jar" -O plantuml.jar && \
    rm -rf /var/lib/apt/lists/*
ENTRYPOINT ["java", "-jar", "plantuml.jar", ""]